apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api-pod
  template:
    metadata:
      labels:
        app: sample-api-pod
    spec:
      containers:
        - name: sample-api-container
          image: __ECR_URL__/sample-api:__IMAGE_TAG__
          env:
            - name: DB_HOST
              value: __RDS_HOST__
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: password
            - name: DB_DATABASE
              value: sampledb
          ports:
            - protocol: TCP
              containerPort: 3000
