version: 0.2
phases:
  pre_build:
    commands:
      - IMAGE_TAG=$(git describe --tags)
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${ECR_URL}
  build:
    commands:
      - cd api # 対象フォルダに移動
      - docker build . -t sample-api:${IMAGE_TAG}
      - docker tag sample-api:${IMAGE_TAG} ${ECR_URL}/sample-api:${IMAGE_TAG}
      - docker push ${ECR_URL}/sample-api:${IMAGE_TAG}

